name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y gettext

    - name: Bootstrap autotools
      run: autoreconf -fi

    - name: configure
      run: ./configure

    - name: Build
      run: make

    - name: Run check
      run: make check

    - name: Run dist
      run: make dist
